global:
  resolve_timeout: 1m
  # Telegram bot API endpoint
  telegram_api_url: 'https://api.telegram.org'

route:
  receiver: 'telegram-notifications'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname']

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token: '${TELEGRAM_BOT_TOKEN}'
    chat_id: ${TELEGRAM_CHAT_ID}
    title: 'Forum API Alert'
    message: |
      Alert: {{ .GroupLabels.alertname }}
      Status: {{ .Status }}
      {{ range .Alerts }}
      Description: {{ .Annotations.description }}
      Summary: {{ .Annotations.summary }}
      {{ end }}
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname'] 