global:
  resolve_timeout: 1m

route:
  receiver: 'telegram-notifications'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname']

receivers:
- name: 'telegram-notifications'
  webhook_configs:
  - url: 'http://alertbot:8080/alert'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname'] 