{
 "title": "ScyllaDB Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ScyllaDB Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(scylla_transport_requests_served[1m])"
    }
   ]
  },
  {
   "title": "ScyllaDB Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(scylla_storage_proxy_coordinator_read_latency)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(scylla_storage_proxy_coordinator_write_latency)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "ScyllaDB Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(scylla_memory_total_memory)",
     "legendFormat": "Total"
    },
    { "expr": "avg(scylla_memory_free_memory)", "legendFormat": "Free" }
   ]
  }
 ]
}