groups:
- name: forum_api_alerts
  rules:
  - alert: HighP99Latency
    expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High P99 API latency"
      description: "P99 API latency is above 500ms for more than 1 minute"

  - alert: HighDBRequestRate
    expr: rate(db_requests_total[1m]) > 100
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High DB request rate"
      description: "Database is experiencing more than 100 RPS for more than 1 minute" 