apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false

  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    isDefault: false
    version: 1
    editable: false 

  - name: scylla-datasource
    type: scylladb-scylla-datasource
    access: proxy
    orgId: 1
    isDefault: false
    jsonData:
      host: 'scylladb:9042'
      datacenter: 'datacenter1'
      keyspace: 'posts'